[[pages]]
path = "ui_index.py"
name = "Index"
icon = "ğŸ "

[[pages]]
path = "ui_download.py"
name = "Download"
icon = "â¬‡ï¸"

[[pages]]
path = "ui_indicators.py"
name = "Indicators"
icon = "ğŸ§®"

[[pages]]
path = "ui_signals.py"
name = "Signals"
icon = "ğŸ’¹"

[[pages]]
path = "ui_testback.py"
name = "Testback"
icon = "ğŸ•µï¸"

[[pages]]
path = "ui_summary.py"
name = "Summary"
icon = "ğ„œ"

[[pages]]
path = "ui_monitor.py"
name = "Monitor"
icon = "ğŸ“º"

[[pages]]
path = "ui_analysis.py"
name = "Analysis"
icon = "ğŸ“Š"